version: 2
updates:
  - package-ecosystem: npm
    directory: "/worker"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels: ["dependencies", "worker"]
    assignees: ["mbroton"]
  - package-ecosystem: docker
    directory: "/worker"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels: ["dependencies", "worker"]
    assignees: ["mbroton"]
