// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, name, hash, prefix, created_at, last_used_at, revoked_at
FROM api_keys
WHERE hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, hash string) (APIKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, hash)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (
    id,
    name,
    hash,
    prefix
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, hash, prefix, created_at, last_used_at, revoked_at
`

type InsertAPIKeyParams struct {
	ID     pgtype.UUID
	Name   string
	Hash   string
	Prefix string
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.Name,
		arg.Hash,
		arg.Prefix,
	)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = $2
WHERE id = $1
RETURNING id, name, hash, prefix, created_at, last_used_at, revoked_at
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.RevokedAt)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :one
UPDATE api_keys
SET last_used_at = $2
WHERE id = $1
RETURNING id, name, hash, prefix, created_at, last_used_at, revoked_at
`

type TouchAPIKeyParams struct {
	ID         pgtype.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, touchAPIKey, arg.ID, arg.LastUsedAt)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
