// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package data

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SessionMode string

const (
	SessionModeDefault   SessionMode = "default"
	SessionModeDedicated SessionMode = "dedicated"
)

func (e *SessionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionMode(s)
	case string:
		*e = SessionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionMode: %T", src)
	}
	return nil
}

type NullSessionMode struct {
	SessionMode SessionMode
	Valid       bool // Valid is true if SessionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionMode) Scan(value interface{}) error {
	if value == nil {
		ns.SessionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionMode), nil
}

type SessionStatus string

const (
	SessionStatusPending   SessionStatus = "pending"
	SessionStatusRunning   SessionStatus = "running"
	SessionStatusCompleted SessionStatus = "completed"
	SessionStatusFailed    SessionStatus = "failed"
	SessionStatusExpired   SessionStatus = "expired"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus
	Valid         bool // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type WorkerStatus string

const (
	WorkerStatusAvailable    WorkerStatus = "available"
	WorkerStatusDraining     WorkerStatus = "draining"
	WorkerStatusStalled      WorkerStatus = "stalled"
	WorkerStatusShuttingDown WorkerStatus = "shutting_down"
)

func (e *WorkerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerStatus(s)
	case string:
		*e = WorkerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerStatus: %T", src)
	}
	return nil
}

type NullWorkerStatus struct {
	WorkerStatus WorkerStatus
	Valid        bool // Valid is true if WorkerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerStatus), nil
}

type APIKey struct {
	ID         uuid.UUID
	Name       string
	Hash       string
	Prefix     string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Session struct {
	ID                uuid.UUID
	WorkerID          uuid.UUID
	Browser           string
	PlaywrightVersion string
	WorkerAddress     string
	Mode              SessionMode
	Status            SessionStatus
	CreatedByKey      *uuid.UUID
	CreatedAt         time.Time
	ExpiresAt         *time.Time
	LastHeartbeat     time.Time
	KeepAliveMs       pgtype.Int4
	ConnectMetadata   []byte
}

type Worker struct {
	ID                uuid.UUID
	Address           string
	Browser           string
	PlaywrightVersion string
	MaxSlots          int32
	Status            WorkerStatus
	LastHeartbeat     time.Time
	LifetimeSessions  int64
	CreatedAt         time.Time
}
