// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningSessionsByWorker = `-- name: CountRunningSessionsByWorker :one
SELECT count(*)
FROM sessions
WHERE worker_id = $1
  AND status = 'running'
`

func (q *Queries) CountRunningSessionsByWorker(ctx context.Context, workerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningSessionsByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSession = `-- name: GetSession :one
SELECT id, worker_id, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    id,
    worker_id,
    mode,
    status,
    created_by_key,
    expires_at,
    last_heartbeat,
    keep_alive_ms,
    connect_metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, worker_id, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

type InsertSessionParams struct {
	ID              pgtype.UUID
	WorkerID        pgtype.UUID
	Mode            SessionMode
	Status          SessionStatus
	CreatedByKey    pgtype.UUID
	ExpiresAt       pgtype.Timestamptz
	LastHeartbeat   pgtype.Timestamptz
	KeepAliveMs     pgtype.Int4
	ConnectMetadata []byte
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.WorkerID,
		arg.Mode,
		arg.Status,
		arg.CreatedByKey,
		arg.ExpiresAt,
		arg.LastHeartbeat,
		arg.KeepAliveMs,
		arg.ConnectMetadata,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const listSessionsByWorker = `-- name: ListSessionsByWorker :many
SELECT id, worker_id, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
FROM sessions
WHERE worker_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListSessionsByWorker(ctx context.Context, workerID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Mode,
			&i.Status,
			&i.CreatedByKey,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastHeartbeat,
			&i.KeepAliveMs,
			&i.ConnectMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSessionHeartbeat = `-- name: RenewSessionHeartbeat :one
UPDATE sessions
SET last_heartbeat = $2
WHERE id = $1
RETURNING id, worker_id, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

type RenewSessionHeartbeatParams struct {
	ID            pgtype.UUID
	LastHeartbeat pgtype.Timestamptz
}

func (q *Queries) RenewSessionHeartbeat(ctx context.Context, arg RenewSessionHeartbeatParams) (Session, error) {
	row := q.db.QueryRow(ctx, renewSessionHeartbeat, arg.ID, arg.LastHeartbeat)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const setSessionStatus = `-- name: SetSessionStatus :one
UPDATE sessions
SET status = $2
WHERE id = $1
RETURNING id, worker_id, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

type SetSessionStatusParams struct {
	ID     pgtype.UUID
	Status SessionStatus
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}
