// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package data

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningSessionsByWorker = `-- name: CountRunningSessionsByWorker :one
SELECT count(*)
FROM sessions
WHERE worker_id = $1
  AND status = 'running'
`

func (q *Queries) CountRunningSessionsByWorker(ctx context.Context, workerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningSessionsByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSession = `-- name: GetSession :one
SELECT id, worker_id, browser, playwright_version, worker_address, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.WorkerAddress,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    id,
    worker_id,
    browser,
    playwright_version,
    worker_address,
    mode,
    status,
    created_by_key,
    expires_at,
    last_heartbeat,
    keep_alive_ms,
    connect_metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    now(),
    $10,
    COALESCE($11::jsonb, '{}'::jsonb)
)
RETURNING id, worker_id, browser, playwright_version, worker_address, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

type InsertSessionParams struct {
	ID                uuid.UUID
	WorkerID          uuid.UUID
	Browser           string
	PlaywrightVersion string
	WorkerAddress     string
	Mode              SessionMode
	Status            SessionStatus
	CreatedByKey      *uuid.UUID
	ExpiresAt         *time.Time
	KeepAliveMs       pgtype.Int4
	ConnectMetadata   []byte
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.WorkerID,
		arg.Browser,
		arg.PlaywrightVersion,
		arg.WorkerAddress,
		arg.Mode,
		arg.Status,
		arg.CreatedByKey,
		arg.ExpiresAt,
		arg.KeepAliveMs,
		arg.ConnectMetadata,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.WorkerAddress,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const listSessionsByWorker = `-- name: ListSessionsByWorker :many
SELECT id, worker_id, browser, playwright_version, worker_address, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
FROM sessions
WHERE worker_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListSessionsByWorkerParams struct {
	WorkerID   uuid.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListSessionsByWorker(ctx context.Context, arg ListSessionsByWorkerParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByWorker, arg.WorkerID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Browser,
			&i.PlaywrightVersion,
			&i.WorkerAddress,
			&i.Mode,
			&i.Status,
			&i.CreatedByKey,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastHeartbeat,
			&i.KeepAliveMs,
			&i.ConnectMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSessionHeartbeat = `-- name: RenewSessionHeartbeat :one
UPDATE sessions
SET last_heartbeat = now()
WHERE id = $1
RETURNING id, worker_id, browser, playwright_version, worker_address, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

func (q *Queries) RenewSessionHeartbeat(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, renewSessionHeartbeat, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.WorkerAddress,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}

const setSessionStatus = `-- name: SetSessionStatus :one
UPDATE sessions
SET status = $2
WHERE id = $1
RETURNING id, worker_id, browser, playwright_version, worker_address, mode, status, created_by_key, created_at, expires_at, last_heartbeat, keep_alive_ms, connect_metadata
`

type SetSessionStatusParams struct {
	ID     uuid.UUID
	Status SessionStatus
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.WorkerAddress,
		&i.Mode,
		&i.Status,
		&i.CreatedByKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastHeartbeat,
		&i.KeepAliveMs,
		&i.ConnectMetadata,
	)
	return i, err
}
