// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers
WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
FROM workers
ORDER BY created_at, id
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Browser,
			&i.PlaywrightVersion,
			&i.MaxSlots,
			&i.Status,
			&i.LastHeartbeat,
			&i.LifetimeSessions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerWorker = `-- name: RegisterWorker :one
INSERT INTO workers (
    id,
    address,
    browser,
    playwright_version,
    max_slots,
    status,
    last_heartbeat
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

type RegisterWorkerParams struct {
	ID                uuid.UUID
	Address           string
	Browser           string
	PlaywrightVersion string
	MaxSlots          int32
	Status            WorkerStatus
}

func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, registerWorker,
		arg.ID,
		arg.Address,
		arg.Browser,
		arg.PlaywrightVersion,
		arg.MaxSlots,
		arg.Status,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const setWorkerStatus = `-- name: SetWorkerStatus :one
UPDATE workers
SET status = $1::worker_status
WHERE id = $2
  AND (
      ($1::worker_status = 'draining' AND status IN ('available', 'draining'))
      OR (
          $1::worker_status = 'shutting_down'
          AND status IN ('available', 'draining', 'shutting_down')
      )
  )
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

type SetWorkerStatusParams struct {
	Status WorkerStatus
	ID     uuid.UUID
}

func (q *Queries) SetWorkerStatus(ctx context.Context, arg SetWorkerStatusParams) (Worker, error) {
	row := q.db.QueryRow(ctx, setWorkerStatus, arg.Status, arg.ID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :one
UPDATE workers
SET last_heartbeat = now(),
    status = CASE
        WHEN status = 'stalled' THEN 'available'
        ELSE status
    END
WHERE id = $1
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerHeartbeat, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}
