// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const countActiveSessionsByWorker = `-- name: CountActiveSessionsByWorker :one
SELECT count(*)
FROM sessions
WHERE worker_id = $1
  AND status IN ('pending', 'running')
`

func (q *Queries) CountActiveSessionsByWorker(ctx context.Context, workerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadWorkers = `-- name: DeleteDeadWorkers :many
DELETE FROM workers AS w
WHERE (
    (
        w.status = 'shutting_down'
        AND w.last_heartbeat < now() - $1::bigint * interval '1 microsecond'
    ) OR (
        w.status = 'stalled'
        AND w.last_heartbeat < now() - $2::bigint * interval '1 microsecond'
    ) OR (
        w.status = 'draining'
        AND w.last_heartbeat < now() - $2::bigint * interval '1 microsecond'
    )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM sessions AS s
      WHERE s.worker_id = w.id
        AND s.status IN ('pending', 'running')
  )
RETURNING w.id
`

type DeleteDeadWorkersParams struct {
	WorkerTtlMicroseconds        int64
	StalledWorkerTtlMicroseconds int64
}

func (q *Queries) DeleteDeadWorkers(ctx context.Context, arg DeleteDeadWorkersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteDeadWorkers, arg.WorkerTtlMicroseconds, arg.StalledWorkerTtlMicroseconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers
WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getCapacityByBrowser = `-- name: GetCapacityByBrowser :many
WITH eligible_workers AS (
    SELECT
        w.browser,
        w.max_slots,
        count(s.id) AS active_count
    FROM workers AS w
    LEFT JOIN sessions AS s
      ON s.worker_id = w.id
     AND s.status IN ('pending', 'running')
    WHERE w.status = 'available'
      AND w.last_heartbeat > now() - $1::bigint * interval '1 microsecond'
      AND (
          $2::bigint = 0
          OR w.lifetime_sessions < $2::bigint
      )
    GROUP BY w.id
), eligible AS (
    SELECT
        browser,
        count(*) AS workers,
        COALESCE(sum(max_slots), 0)::bigint AS max_slots,
        COALESCE(sum(GREATEST(max_slots::bigint - active_count, 0)), 0)::bigint AS available_slots
    FROM eligible_workers
    GROUP BY browser
), active AS (
    SELECT browser, count(*) AS active_sessions
    FROM sessions
    WHERE status IN ('pending', 'running')
    GROUP BY browser
), browsers AS (
    SELECT browser FROM eligible
    UNION
    SELECT browser FROM active
)
SELECT
    browsers.browser::text AS browser,
    COALESCE(eligible.workers, 0)::bigint AS workers,
    COALESCE(eligible.max_slots, 0)::bigint AS max_slots,
    COALESCE(active.active_sessions, 0)::bigint AS active_sessions,
    COALESCE(eligible.available_slots, 0)::bigint AS available_slots
FROM browsers
LEFT JOIN eligible USING (browser)
LEFT JOIN active USING (browser)
ORDER BY browsers.browser
`

type GetCapacityByBrowserParams struct {
	WorkerTtlMicroseconds int64
	MaxLifetimeSessions   int64
}

type GetCapacityByBrowserRow struct {
	Browser        string
	Workers        int64
	MaxSlots       int64
	ActiveSessions int64
	AvailableSlots int64
}

func (q *Queries) GetCapacityByBrowser(ctx context.Context, arg GetCapacityByBrowserParams) ([]GetCapacityByBrowserRow, error) {
	rows, err := q.db.Query(ctx, getCapacityByBrowser, arg.WorkerTtlMicroseconds, arg.MaxLifetimeSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCapacityByBrowserRow
	for rows.Next() {
		var i GetCapacityByBrowserRow
		if err := rows.Scan(
			&i.Browser,
			&i.Workers,
			&i.MaxSlots,
			&i.ActiveSessions,
			&i.AvailableSlots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorker = `-- name: GetWorker :one
SELECT id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const incrementWorkerLifetimeSessions = `-- name: IncrementWorkerLifetimeSessions :one
UPDATE workers
SET lifetime_sessions = lifetime_sessions + 1
WHERE id = $1
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

func (q *Queries) IncrementWorkerLifetimeSessions(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerLifetimeSessions, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
FROM workers
ORDER BY created_at, id
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Browser,
			&i.PlaywrightVersion,
			&i.MaxSlots,
			&i.Status,
			&i.LastHeartbeat,
			&i.LifetimeSessions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyCapacityChanged = `-- name: NotifyCapacityChanged :exec
SELECT pg_notify('capacity_changed', '')
`

func (q *Queries) NotifyCapacityChanged(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyCapacityChanged)
	return err
}

const registerWorker = `-- name: RegisterWorker :one
INSERT INTO workers (
    id,
    address,
    browser,
    playwright_version,
    max_slots,
    status,
    last_heartbeat
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

type RegisterWorkerParams struct {
	ID                uuid.UUID
	Address           string
	Browser           string
	PlaywrightVersion string
	MaxSlots          int32
	Status            WorkerStatus
}

func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, registerWorker,
		arg.ID,
		arg.Address,
		arg.Browser,
		arg.PlaywrightVersion,
		arg.MaxSlots,
		arg.Status,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const selectClaimableWorker = `-- name: SelectClaimableWorker :one
SELECT w.id, w.address, w.browser, w.playwright_version, w.max_slots, w.status, w.last_heartbeat, w.lifetime_sessions, w.created_at
FROM workers AS w
CROSS JOIN LATERAL (
    SELECT count(*) AS active_count
    FROM sessions AS s
    WHERE s.worker_id = w.id
      AND s.status IN ('pending', 'running')
) AS active
WHERE w.status = 'available'
  AND w.browser = $1
  AND w.last_heartbeat > now() - $2::bigint * interval '1 microsecond'
  AND (
      $3::bigint = 0
      OR w.lifetime_sessions < $3::bigint
  )
  AND active.active_count < w.max_slots
  AND w.id != ALL($4::uuid[])
ORDER BY w.lifetime_sessions DESC, active.active_count ASC, w.id
FOR UPDATE OF w SKIP LOCKED
LIMIT 1
`

type SelectClaimableWorkerParams struct {
	Browser               string
	WorkerTtlMicroseconds int64
	MaxLifetimeSessions   int64
	ExcludedIds           []uuid.UUID
}

// Prefer the oldest worker, then the least loaded worker, so workers reach
// the lifetime limit and recycle one at a time instead of as a fleet.
func (q *Queries) SelectClaimableWorker(ctx context.Context, arg SelectClaimableWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, selectClaimableWorker,
		arg.Browser,
		arg.WorkerTtlMicroseconds,
		arg.MaxLifetimeSessions,
		arg.ExcludedIds,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const setWorkerStatus = `-- name: SetWorkerStatus :one
UPDATE workers
SET status = $1::worker_status
WHERE id = $2
  AND (
      ($1::worker_status = 'draining' AND status IN ('available', 'draining'))
      OR (
          $1::worker_status = 'shutting_down'
          AND status IN ('available', 'draining', 'stalled', 'shutting_down')
      )
  )
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

type SetWorkerStatusParams struct {
	Status WorkerStatus
	ID     uuid.UUID
}

func (q *Queries) SetWorkerStatus(ctx context.Context, arg SetWorkerStatusParams) (Worker, error) {
	row := q.db.QueryRow(ctx, setWorkerStatus, arg.Status, arg.ID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}

const stallSilentWorkers = `-- name: StallSilentWorkers :execrows
UPDATE workers
SET status = 'stalled'
WHERE status = 'available'
  AND last_heartbeat < now() - $1::bigint * interval '1 microsecond'
`

// This predicate is load-bearing. The heartbeat can revive stalled workers
// only because this sweep never overwrites drain or shutdown intent.
func (q *Queries) StallSilentWorkers(ctx context.Context, workerTtlMicroseconds int64) (int64, error) {
	result, err := q.db.Exec(ctx, stallSilentWorkers, workerTtlMicroseconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :one
UPDATE workers
SET last_heartbeat = now(),
    -- A heartbeat can revive stalled workers only because the rescuer may mark
    -- available workers stalled; it must never overwrite drain or shutdown intent.
    status = CASE
        WHEN status = 'stalled' THEN 'available'
        ELSE status
    END
WHERE id = $1
RETURNING id, address, browser, playwright_version, max_slots, status, last_heartbeat, lifetime_sessions, created_at
`

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerHeartbeat, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Browser,
		&i.PlaywrightVersion,
		&i.MaxSlots,
		&i.Status,
		&i.LastHeartbeat,
		&i.LifetimeSessions,
		&i.CreatedAt,
	)
	return i, err
}
