// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateSessionData, CreateSessionErrors, CreateSessionResponses, GetCapacityData, GetCapacityErrors, GetCapacityResponses, GetSessionData, GetSessionErrors, GetSessionResponses, HealthData, HealthErrors, HealthResponses, HeartbeatWorkerData, HeartbeatWorkerErrors, HeartbeatWorkerResponses, ListWorkersData, ListWorkersErrors, ListWorkersResponses, ReadinessData, ReadinessErrors, ReadinessResponses, RegisterWorkerData, RegisterWorkerErrors, RegisterWorkerResponses, SetWorkerStatusData, SetWorkerStatusErrors, SetWorkerStatusResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check process health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, HealthErrors, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Register a worker
 */
export const registerWorker = <ThrowOnError extends boolean = false>(options: Options<RegisterWorkerData, ThrowOnError>) => (options.client ?? client).post<RegisterWorkerResponses, RegisterWorkerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/internal/workers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Heartbeat a worker
 */
export const heartbeatWorker = <ThrowOnError extends boolean = false>(options: Options<HeartbeatWorkerData, ThrowOnError>) => (options.client ?? client).post<HeartbeatWorkerResponses, HeartbeatWorkerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/internal/workers/{id}/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request a worker status transition
 */
export const setWorkerStatus = <ThrowOnError extends boolean = false>(options: Options<SetWorkerStatusData, ThrowOnError>) => (options.client ?? client).post<SetWorkerStatusResponses, SetWorkerStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/internal/workers/{id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check database readiness
 */
export const readiness = <ThrowOnError extends boolean = false>(options?: Options<ReadinessData, ThrowOnError>) => (options?.client ?? client).get<ReadinessResponses, ReadinessErrors, ThrowOnError>({ url: '/readyz', ...options });

/**
 * Get session capacity
 */
export const getCapacity = <ThrowOnError extends boolean = false>(options?: Options<GetCapacityData, ThrowOnError>) => (options?.client ?? client).get<GetCapacityResponses, GetCapacityErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/capacity',
    ...options
});

/**
 * Create a session
 */
export const createSession = <ThrowOnError extends boolean = false>(options: Options<CreateSessionData, ThrowOnError>) => (options.client ?? client).post<CreateSessionResponses, CreateSessionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a session
 */
export const getSession = <ThrowOnError extends boolean = false>(options: Options<GetSessionData, ThrowOnError>) => (options.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sessions/{id}',
    ...options
});

/**
 * List workers
 */
export const listWorkers = <ThrowOnError extends boolean = false>(options?: Options<ListWorkersData, ThrowOnError>) => (options?.client ?? client).get<ListWorkersResponses, ListWorkersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workers',
    ...options
});
