// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: string;
};

export type HeartbeatInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active_session_ids?: Array<string> | null;
};

export type HeartbeatOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    commands: Array<string>;
    status: 'available' | 'draining' | 'stalled' | 'shutting_down';
};

export type RegisterWorkerInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address: string;
    browser: 'chromium' | 'firefox' | 'webkit';
    max_slots: number;
    playwright_version: string;
};

export type Session = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    browser: string;
    connect_metadata: {
        [key: string]: unknown;
    };
    created_at: string;
    created_by_key?: string;
    expires_at?: string;
    id: string;
    keep_alive_ms?: number;
    last_heartbeat: string;
    mode: 'default' | 'dedicated';
    playwright_version: string;
    status: 'pending' | 'running' | 'completed' | 'failed' | 'expired';
    worker_address: string;
    worker_id: string;
};

export type SetStatusInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: 'draining' | 'shutting_down';
};

export type Worker = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address: string;
    browser: string;
    created_at: string;
    id: string;
    last_heartbeat: string;
    lifetime_sessions: number;
    max_slots: number;
    playwright_version: string;
    status: 'available' | 'draining' | 'stalled' | 'shutting_down';
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthOutputBodyWritable = {
    status: string;
};

export type HeartbeatInputBodyWritable = {
    active_session_ids?: Array<string> | null;
};

export type HeartbeatOutputBodyWritable = {
    commands: Array<string>;
    status: 'available' | 'draining' | 'stalled' | 'shutting_down';
};

export type RegisterWorkerInputBodyWritable = {
    address: string;
    browser: 'chromium' | 'firefox' | 'webkit';
    max_slots: number;
    playwright_version: string;
};

export type SessionWritable = {
    browser: string;
    connect_metadata: {
        [key: string]: unknown;
    };
    created_at: string;
    created_by_key?: string;
    expires_at?: string;
    id: string;
    keep_alive_ms?: number;
    last_heartbeat: string;
    mode: 'default' | 'dedicated';
    playwright_version: string;
    status: 'pending' | 'running' | 'completed' | 'failed' | 'expired';
    worker_address: string;
    worker_id: string;
};

export type SetStatusInputBodyWritable = {
    status: 'draining' | 'shutting_down';
};

export type WorkerWritable = {
    address: string;
    browser: string;
    created_at: string;
    id: string;
    last_heartbeat: string;
    lifetime_sessions: number;
    max_slots: number;
    playwright_version: string;
    status: 'available' | 'draining' | 'stalled' | 'shutting_down';
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type RegisterWorkerData = {
    body: RegisterWorkerInputBodyWritable;
    path?: never;
    query?: never;
    url: '/internal/workers';
};

export type RegisterWorkerErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RegisterWorkerError = RegisterWorkerErrors[keyof RegisterWorkerErrors];

export type RegisterWorkerResponses = {
    /**
     * Created
     */
    201: Worker;
};

export type RegisterWorkerResponse = RegisterWorkerResponses[keyof RegisterWorkerResponses];

export type HeartbeatWorkerData = {
    body: HeartbeatInputBodyWritable;
    path: {
        /**
         * Worker ID
         */
        id: string;
    };
    query?: never;
    url: '/internal/workers/{id}/heartbeat';
};

export type HeartbeatWorkerErrors = {
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type HeartbeatWorkerError = HeartbeatWorkerErrors[keyof HeartbeatWorkerErrors];

export type HeartbeatWorkerResponses = {
    /**
     * OK
     */
    200: HeartbeatOutputBody;
};

export type HeartbeatWorkerResponse = HeartbeatWorkerResponses[keyof HeartbeatWorkerResponses];

export type SetWorkerStatusData = {
    body: SetStatusInputBodyWritable;
    path: {
        /**
         * Worker ID
         */
        id: string;
    };
    query?: never;
    url: '/internal/workers/{id}/status';
};

export type SetWorkerStatusErrors = {
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type SetWorkerStatusError = SetWorkerStatusErrors[keyof SetWorkerStatusErrors];

export type SetWorkerStatusResponses = {
    /**
     * OK
     */
    200: Worker;
};

export type SetWorkerStatusResponse = SetWorkerStatusResponses[keyof SetWorkerStatusResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadinessErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorModel;
    /**
     * Service Unavailable
     */
    503: ErrorModel;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type ReadinessResponse = ReadinessResponses[keyof ReadinessResponses];

export type GetSessionData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/sessions/{id}';
};

export type GetSessionErrors = {
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * OK
     */
    200: Session;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type ListWorkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/workers';
};

export type ListWorkersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListWorkersError = ListWorkersErrors[keyof ListWorkersErrors];

export type ListWorkersResponses = {
    /**
     * OK
     */
    200: Array<Worker>;
};

export type ListWorkersResponse = ListWorkersResponses[keyof ListWorkersResponses];
