name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build proxy (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./proxy
          file: ./proxy/Dockerfile
          push: false
          platforms: linux/amd64

      - name: Build worker (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: false
          platforms: linux/amd64
